language: node_js

node_js:
  - "4"

branches:
  only:
    - master
    - gh-pages
    
install:
  - npm install gitbook-cli -g
  - gitbook install
  
script:
  - gitbook build
  - git branch
  - git checkout gh-pages
  - git status
  - echo 'hit'